/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as NovaSenhaRouteImport } from './routes/nova-senha'

import { Route as AuthenticatedBemVindoRouteImport } from './routes/_authenticated/bem-vindo'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedContasRouteImport } from './routes/_authenticated/contas'
import { Route as AuthenticatedCookiesRouteImport } from './routes/_authenticated/cookies'
import { Route as AuthenticatedInvestimentosRouteImport } from './routes/_authenticated/investimentos'
import { Route as AuthenticatedMetasRouteImport } from './routes/_authenticated/metas'
import { Route as AuthenticatedMovimentacoesRouteImport } from './routes/_authenticated/movimentacoes'
import { Route as AuthenticatedOrganizarSalarioRouteImport } from './routes/_authenticated/organizar-salario'
import { Route as AuthenticatedPlanejamentoRouteImport } from './routes/_authenticated/planejamento'
import { Route as AuthenticatedPoliticaDePrivacidadeRouteImport } from './routes/_authenticated/politica-de-privacidade'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedReservaRouteImport } from './routes/_authenticated/reserva'
import { Route as AuthenticatedTermosDeUsoRouteImport } from './routes/_authenticated/termos-de-uso'
import { Route as AuthenticatedVisaoGeralRouteImport } from './routes/_authenticated/visao-geral'

import { Route as AuthenticatedConfiguracaoAparenciaRouteImport } from './routes/_authenticated/configuracao/aparencia'
import { Route as AuthenticatedConfiguracaoContaRouteImport } from './routes/_authenticated/configuracao/conta'
import { Route as AuthenticatedConfiguracaoContaEmailRouteImport } from './routes/_authenticated/configuracao/conta.email'
import { Route as AuthenticatedConfiguracaoContaSenhaRouteImport } from './routes/_authenticated/configuracao/conta.senha'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)

const NovaSenhaRoute = NovaSenhaRouteImport.update({
  id: '/nova-senha',
  path: '/nova-senha',
  getParentRoute: () => rootRouteImport,
} as any)

const AuthenticatedBemVindoRoute =
  AuthenticatedBemVindoRouteImport.update({
    id: '/bem-vindo',
    path: '/bem-vindo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedContasRoute =
  AuthenticatedContasRouteImport.update({
    id: '/contas',
    path: '/contas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedCookiesRoute =
  AuthenticatedCookiesRouteImport.update({
    id: '/cookies',
    path: '/cookies',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedInvestimentosRoute =
  AuthenticatedInvestimentosRouteImport.update({
    id: '/investimentos',
    path: '/investimentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedMetasRoute =
  AuthenticatedMetasRouteImport.update({
    id: '/metas',
    path: '/metas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedMovimentacoesRoute =
  AuthenticatedMovimentacoesRouteImport.update({
    id: '/movimentacoes',
    path: '/movimentacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedOrganizarSalarioRoute =
  AuthenticatedOrganizarSalarioRouteImport.update({
    id: '/organizar-salario',
    path: '/organizar-salario',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedPlanejamentoRoute =
  AuthenticatedPlanejamentoRouteImport.update({
    id: '/planejamento',
    path: '/planejamento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedPoliticaDePrivacidadeRoute =
  AuthenticatedPoliticaDePrivacidadeRouteImport.update({
    id: '/politica-de-privacidade',
    path: '/politica-de-privacidade',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedRelatoriosRoute =
  AuthenticatedRelatoriosRouteImport.update({
    id: '/relatorios',
    path: '/relatorios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedReservaRoute =
  AuthenticatedReservaRouteImport.update({
    id: '/reserva',
    path: '/reserva',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedTermosDeUsoRoute =
  AuthenticatedTermosDeUsoRouteImport.update({
    id: '/termos-de-uso',
    path: '/termos-de-uso',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedVisaoGeralRoute =
  AuthenticatedVisaoGeralRouteImport.update({
    id: '/visao-geral',
    path: '/visao-geral',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedConfiguracaoAparenciaRoute =
  AuthenticatedConfiguracaoAparenciaRouteImport.update({
    id: '/configuracao/aparencia',
    path: '/configuracao/aparencia',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedConfiguracaoContaRoute =
  AuthenticatedConfiguracaoContaRouteImport.update({
    id: '/configuracao/conta',
    path: '/configuracao/conta',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedConfiguracaoContaEmailRoute =
  AuthenticatedConfiguracaoContaEmailRouteImport.update({
    id: '/configuracao/conta.email',
    path: '/configuracao/conta.email',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedConfiguracaoContaSenhaRoute =
  AuthenticatedConfiguracaoContaSenhaRouteImport.update({
    id: '/configuracao/conta.senha',
    path: '/configuracao/conta.senha',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/nova-senha': typeof NovaSenhaRoute
  '/bem-vindo': typeof AuthenticatedBemVindoRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/contas': typeof AuthenticatedContasRoute
  '/cookies': typeof AuthenticatedCookiesRoute
  '/investimentos': typeof AuthenticatedInvestimentosRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/movimentacoes': typeof AuthenticatedMovimentacoesRoute
  '/organizar-salario': typeof AuthenticatedOrganizarSalarioRoute
  '/planejamento': typeof AuthenticatedPlanejamentoRoute
  '/politica-de-privacidade': typeof AuthenticatedPoliticaDePrivacidadeRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/reserva': typeof AuthenticatedReservaRoute
  '/termos-de-uso': typeof AuthenticatedTermosDeUsoRoute
  '/visao-geral': typeof AuthenticatedVisaoGeralRoute
  '/configuracao/aparencia': typeof AuthenticatedConfiguracaoAparenciaRoute
  '/configuracao/conta': typeof AuthenticatedConfiguracaoContaRoute
  '/configuracao/conta.email': typeof AuthenticatedConfiguracaoContaEmailRoute
  '/configuracao/conta.senha': typeof AuthenticatedConfiguracaoContaSenhaRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/nova-senha': typeof NovaSenhaRoute
  '/bem-vindo': typeof AuthenticatedBemVindoRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/contas': typeof AuthenticatedContasRoute
  '/cookies': typeof AuthenticatedCookiesRoute
  '/investimentos': typeof AuthenticatedInvestimentosRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/movimentacoes': typeof AuthenticatedMovimentacoesRoute
  '/organizar-salario': typeof AuthenticatedOrganizarSalarioRoute
  '/planejamento': typeof AuthenticatedPlanejamentoRoute
  '/politica-de-privacidade': typeof AuthenticatedPoliticaDePrivacidadeRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/reserva': typeof AuthenticatedReservaRoute
  '/termos-de-uso': typeof AuthenticatedTermosDeUsoRoute
  '/visao-geral': typeof AuthenticatedVisaoGeralRoute
  '/configuracao/aparencia': typeof AuthenticatedConfiguracaoAparenciaRoute
  '/configuracao/conta': typeof AuthenticatedConfiguracaoContaRoute
  '/configuracao/conta.email': typeof AuthenticatedConfiguracaoContaEmailRoute
  '/configuracao/conta.senha': typeof AuthenticatedConfiguracaoContaSenhaRoute
}

export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/nova-senha': typeof NovaSenhaRoute
  '/_authenticated/bem-vindo': typeof AuthenticatedBemVindoRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/contas': typeof AuthenticatedContasRoute
  '/_authenticated/cookies': typeof AuthenticatedCookiesRoute
  '/_authenticated/investimentos': typeof AuthenticatedInvestimentosRoute
  '/_authenticated/metas': typeof AuthenticatedMetasRoute
  '/_authenticated/movimentacoes': typeof AuthenticatedMovimentacoesRoute
  '/_authenticated/organizar-salario': typeof AuthenticatedOrganizarSalarioRoute
  '/_authenticated/planejamento': typeof AuthenticatedPlanejamentoRoute
  '/_authenticated/politica-de-privacidade': typeof AuthenticatedPoliticaDePrivacidadeRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/reserva': typeof AuthenticatedReservaRoute
  '/_authenticated/termos-de-uso': typeof AuthenticatedTermosDeUsoRoute
  '/_authenticated/visao-geral': typeof AuthenticatedVisaoGeralRoute
  '/_authenticated/configuracao/aparencia': typeof AuthenticatedConfiguracaoAparenciaRoute
  '/_authenticated/configuracao/conta': typeof AuthenticatedConfiguracaoContaRoute
  '/_authenticated/configuracao/conta.email': typeof AuthenticatedConfiguracaoContaEmailRoute
  '/_authenticated/configuracao/conta.senha': typeof AuthenticatedConfiguracaoContaSenhaRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/nova-senha'
    | '/bem-vindo'
    | '/configuracoes'
    | '/contas'
    | '/cookies'
    | '/investimentos'
    | '/metas'
    | '/movimentacoes'
    | '/organizar-salario'
    | '/planejamento'
    | '/politica-de-privacidade'
    | '/relatorios'
    | '/reserva'
    | '/termos-de-uso'
    | '/visao-geral'
    | '/configuracao/aparencia'
    | '/configuracao/conta'
    | '/configuracao/conta.email'
    | '/configuracao/conta.senha'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/nova-senha'
    | '/bem-vindo'
    | '/configuracoes'
    | '/contas'
    | '/cookies'
    | '/investimentos'
    | '/metas'
    | '/movimentacoes'
    | '/organizar-salario'
    | '/planejamento'
    | '/politica-de-privacidade'
    | '/relatorios'
    | '/reserva'
    | '/termos-de-uso'
    | '/visao-geral'
    | '/configuracao/aparencia'
    | '/configuracao/conta'
    | '/configuracao/conta.email'
    | '/configuracao/conta.senha'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/nova-senha'
    | '/_authenticated/bem-vindo'
    | '/_authenticated/configuracoes'
    | '/_authenticated/contas'
    | '/_authenticated/cookies'
    | '/_authenticated/investimentos'
    | '/_authenticated/metas'
    | '/_authenticated/movimentacoes'
    | '/_authenticated/organizar-salario'
    | '/_authenticated/planejamento'
    | '/_authenticated/politica-de-privacidade'
    | '/_authenticated/relatorios'
    | '/_authenticated/reserva'
    | '/_authenticated/termos-de-uso'
    | '/_authenticated/visao-geral'
    | '/_authenticated/configuracao/aparencia'
    | '/_authenticated/configuracao/conta'
    | '/_authenticated/configuracao/conta.email'
    | '/_authenticated/configuracao/conta.senha'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  NovaSenhaRoute: typeof NovaSenhaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }

    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }

    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }

    '/nova-senha': {
      id: '/nova-senha'
      path: '/nova-senha'
      fullPath: '/nova-senha'
      preLoaderRoute: typeof NovaSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }

    '/_authenticated/bem-vindo': {
      id: '/_authenticated/bem-vindo'
      path: '/bem-vindo'
      fullPath: '/bem-vindo'
      preLoaderRoute: typeof AuthenticatedBemVindoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }

    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }

    '/_authenticated/contas': {
      id: '/_authenticated/contas'
      path: '/contas'
      fullPath: '/contas'
      preLoaderRoute: typeof AuthenticatedContasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }

    '/_authenticated/cookies': {
      id: '/_authenticated/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof AuthenticatedCookiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }

    '/_authenticated/investimentos': {
      id: '/_authenticated/investimentos'
      path: '/investimentos'
      fullPath: '/investimentos'
      preLoaderRoute: typeof AuthenticatedInvestimentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }

    '/_authenticated/metas': {
      id: '/_authenticated/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof AuthenticatedMetasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }

    '/_authenticated/movimentacoes': {
      id: '/_authenticated/movimentacoes'
      path: '/movimentacoes'
      fullPath: '/movimentacoes'
      preLoaderRoute: typeof AuthenticatedMovimentacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }

    '/_authenticated/organizar-salario': {
      id: '/_authenticated/organizar-salario'
      path: '/organizar-salario'
      fullPath: '/organizar-salario'
      preLoaderRoute: typeof AuthenticatedOrganizarSalarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }

    '/_authenticated/planejamento': {
      id: '/_authenticated/planejamento'
      path: '/planejamento'
      fullPath: '/planejamento'
      preLoaderRoute: typeof AuthenticatedPlanejamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }

    '/_authenticated/politica-de-privacidade': {
      id: '/_authenticated/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof AuthenticatedPoliticaDePrivacidadeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }

    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }

    '/_authenticated/reserva': {
      id: '/_authenticated/reserva'
      path: '/reserva'
      fullPath: '/reserva'
      preLoaderRoute: typeof AuthenticatedReservaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }

    '/_authenticated/termos-de-uso': {
      id: '/_authenticated/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof AuthenticatedTermosDeUsoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }

    '/_authenticated/visao-geral': {
      id: '/_authenticated/visao-geral'
      path: '/visao-geral'
      fullPath: '/visao-geral'
      preLoaderRoute: typeof AuthenticatedVisaoGeralRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }

    '/_authenticated/configuracao/aparencia': {
      id: '/_authenticated/configuracao/aparencia'
      path: '/configuracao/aparencia'
      fullPath: '/configuracao/aparencia'
      preLoaderRoute: typeof AuthenticatedConfiguracaoAparenciaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }

    '/_authenticated/configuracao/conta': {
      id: '/_authenticated/configuracao/conta'
      path: '/configuracao/conta'
      fullPath: '/configuracao/conta'
      preLoaderRoute: typeof AuthenticatedConfiguracaoContaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }

    '/_authenticated/configuracao/conta.email': {
      id: '/_authenticated/configuracao/conta.email'
      path: '/configuracao/conta.email'
      fullPath: '/configuracao/conta.email'
      preLoaderRoute: typeof AuthenticatedConfiguracaoContaEmailRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }

    '/_authenticated/configuracao/conta.senha': {
      id: '/_authenticated/configuracao/conta.senha'
      path: '/configuracao/conta.senha'
      fullPath: '/configuracao/conta.senha'
      preLoaderRoute: typeof AuthenticatedConfiguracaoContaSenhaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBemVindoRoute: typeof AuthenticatedBemVindoRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedContasRoute: typeof AuthenticatedContasRoute
  AuthenticatedCookiesRoute: typeof AuthenticatedCookiesRoute
  AuthenticatedInvestimentosRoute: typeof AuthenticatedInvestimentosRoute
  AuthenticatedMetasRoute: typeof AuthenticatedMetasRoute
  AuthenticatedMovimentacoesRoute: typeof AuthenticatedMovimentacoesRoute
  AuthenticatedOrganizarSalarioRoute: typeof AuthenticatedOrganizarSalarioRoute
  AuthenticatedPlanejamentoRoute: typeof AuthenticatedPlanejamentoRoute
  AuthenticatedPoliticaDePrivacidadeRoute: typeof AuthenticatedPoliticaDePrivacidadeRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedReservaRoute: typeof AuthenticatedReservaRoute
  AuthenticatedTermosDeUsoRoute: typeof AuthenticatedTermosDeUsoRoute
  AuthenticatedVisaoGeralRoute: typeof AuthenticatedVisaoGeralRoute
  AuthenticatedConfiguracaoAparenciaRoute: typeof AuthenticatedConfiguracaoAparenciaRoute
  AuthenticatedConfiguracaoContaRoute: typeof AuthenticatedConfiguracaoContaRoute
  AuthenticatedConfiguracaoContaEmailRoute: typeof AuthenticatedConfiguracaoContaEmailRoute
  AuthenticatedConfiguracaoContaSenhaRoute: typeof AuthenticatedConfiguracaoContaSenhaRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBemVindoRoute,
  AuthenticatedConfiguracoesRoute,
  AuthenticatedContasRoute,
  AuthenticatedCookiesRoute,
  AuthenticatedInvestimentosRoute,
  AuthenticatedMetasRoute,
  AuthenticatedMovimentacoesRoute,
  AuthenticatedOrganizarSalarioRoute,
  AuthenticatedPlanejamentoRoute,
  AuthenticatedPoliticaDePrivacidadeRoute,
  AuthenticatedRelatoriosRoute,
  AuthenticatedReservaRoute,
  AuthenticatedTermosDeUsoRoute,
  AuthenticatedVisaoGeralRoute,
  AuthenticatedConfiguracaoAparenciaRoute,
  AuthenticatedConfiguracaoContaRoute,
  AuthenticatedConfiguracaoContaEmailRoute,
  AuthenticatedConfiguracaoContaSenhaRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(
    AuthenticatedRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute,
  NovaSenhaRoute,
}

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'

declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}