/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedBemVindoRouteImport } from './routes/_authenticated/bem-vindo'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedContasRouteImport } from './routes/_authenticated/contas'
import { Route as AuthenticatedInvestimentosRouteImport } from './routes/_authenticated/investimentos'
import { Route as AuthenticatedMetasRouteImport } from './routes/_authenticated/metas'
import { Route as AuthenticatedMovimentacoesRouteImport } from './routes/_authenticated/movimentacoes'
import { Route as AuthenticatedOrganizarSalarioRouteImport } from './routes/_authenticated/organizar-salario'
import { Route as AuthenticatedPlanejamentoRouteImport } from './routes/_authenticated/planejamento'
import { Route as AuthenticatedReservaRouteImport } from './routes/_authenticated/reserva'
import { Route as AuthenticatedVisaoGeralRouteImport } from './routes/_authenticated/visao-geral'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBemVindoRoute = AuthenticatedBemVindoRouteImport.update({
  id: '/bem-vindo',
  path: '/bem-vindo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContasRoute = AuthenticatedContasRouteImport.update({
  id: '/contas',
  path: '/contas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvestimentosRoute =
  AuthenticatedInvestimentosRouteImport.update({
    id: '/investimentos',
    path: '/investimentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMetasRoute = AuthenticatedMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMovimentacoesRoute =
  AuthenticatedMovimentacoesRouteImport.update({
    id: '/movimentacoes',
    path: '/movimentacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrganizarSalarioRoute =
  AuthenticatedOrganizarSalarioRouteImport.update({
    id: '/organizar-salario',
    path: '/organizar-salario',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlanejamentoRoute =
  AuthenticatedPlanejamentoRouteImport.update({
    id: '/planejamento',
    path: '/planejamento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReservaRoute = AuthenticatedReservaRouteImport.update({
  id: '/reserva',
  path: '/reserva',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVisaoGeralRoute = AuthenticatedVisaoGeralRouteImport.update({
  id: '/visao-geral',
  path: '/visao-geral',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bem-vindo': typeof AuthenticatedBemVindoRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/contas': typeof AuthenticatedContasRoute
  '/investimentos': typeof AuthenticatedInvestimentosRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/movimentacoes': typeof AuthenticatedMovimentacoesRoute
  '/organizar-salario': typeof AuthenticatedOrganizarSalarioRoute
  '/planejamento': typeof AuthenticatedPlanejamentoRoute
  '/reserva': typeof AuthenticatedReservaRoute
  '/visao-geral': typeof AuthenticatedVisaoGeralRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bem-vindo': typeof AuthenticatedBemVindoRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/contas': typeof AuthenticatedContasRoute
  '/investimentos': typeof AuthenticatedInvestimentosRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/movimentacoes': typeof AuthenticatedMovimentacoesRoute
  '/organizar-salario': typeof AuthenticatedOrganizarSalarioRoute
  '/planejamento': typeof AuthenticatedPlanejamentoRoute
  '/reserva': typeof AuthenticatedReservaRoute
  '/visao-geral': typeof AuthenticatedVisaoGeralRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/bem-vindo': typeof AuthenticatedBemVindoRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/contas': typeof AuthenticatedContasRoute
  '/_authenticated/investimentos': typeof AuthenticatedInvestimentosRoute
  '/_authenticated/metas': typeof AuthenticatedMetasRoute
  '/_authenticated/movimentacoes': typeof AuthenticatedMovimentacoesRoute
  '/_authenticated/organizar-salario': typeof AuthenticatedOrganizarSalarioRoute
  '/_authenticated/planejamento': typeof AuthenticatedPlanejamentoRoute
  '/_authenticated/reserva': typeof AuthenticatedReservaRoute
  '/_authenticated/visao-geral': typeof AuthenticatedVisaoGeralRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bem-vindo'
    | '/configuracoes'
    | '/contas'
    | '/investimentos'
    | '/metas'
    | '/movimentacoes'
    | '/organizar-salario'
    | '/planejamento'
    | '/reserva'
    | '/visao-geral'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bem-vindo'
    | '/configuracoes'
    | '/contas'
    | '/investimentos'
    | '/metas'
    | '/movimentacoes'
    | '/organizar-salario'
    | '/planejamento'
    | '/reserva'
    | '/visao-geral'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/bem-vindo'
    | '/_authenticated/configuracoes'
    | '/_authenticated/contas'
    | '/_authenticated/investimentos'
    | '/_authenticated/metas'
    | '/_authenticated/movimentacoes'
    | '/_authenticated/organizar-salario'
    | '/_authenticated/planejamento'
    | '/_authenticated/reserva'
    | '/_authenticated/visao-geral'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/bem-vindo': {
      id: '/_authenticated/bem-vindo'
      path: '/bem-vindo'
      fullPath: '/bem-vindo'
      preLoaderRoute: typeof AuthenticatedBemVindoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contas': {
      id: '/_authenticated/contas'
      path: '/contas'
      fullPath: '/contas'
      preLoaderRoute: typeof AuthenticatedContasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/investimentos': {
      id: '/_authenticated/investimentos'
      path: '/investimentos'
      fullPath: '/investimentos'
      preLoaderRoute: typeof AuthenticatedInvestimentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/metas': {
      id: '/_authenticated/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof AuthenticatedMetasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/movimentacoes': {
      id: '/_authenticated/movimentacoes'
      path: '/movimentacoes'
      fullPath: '/movimentacoes'
      preLoaderRoute: typeof AuthenticatedMovimentacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/organizar-salario': {
      id: '/_authenticated/organizar-salario'
      path: '/organizar-salario'
      fullPath: '/organizar-salario'
      preLoaderRoute: typeof AuthenticatedOrganizarSalarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planejamento': {
      id: '/_authenticated/planejamento'
      path: '/planejamento'
      fullPath: '/planejamento'
      preLoaderRoute: typeof AuthenticatedPlanejamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reserva': {
      id: '/_authenticated/reserva'
      path: '/reserva'
      fullPath: '/reserva'
      preLoaderRoute: typeof AuthenticatedReservaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/visao-geral': {
      id: '/_authenticated/visao-geral'
      path: '/visao-geral'
      fullPath: '/visao-geral'
      preLoaderRoute: typeof AuthenticatedVisaoGeralRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBemVindoRoute: typeof AuthenticatedBemVindoRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedContasRoute: typeof AuthenticatedContasRoute
  AuthenticatedInvestimentosRoute: typeof AuthenticatedInvestimentosRoute
  AuthenticatedMetasRoute: typeof AuthenticatedMetasRoute
  AuthenticatedMovimentacoesRoute: typeof AuthenticatedMovimentacoesRoute
  AuthenticatedOrganizarSalarioRoute: typeof AuthenticatedOrganizarSalarioRoute
  AuthenticatedPlanejamentoRoute: typeof AuthenticatedPlanejamentoRoute
  AuthenticatedReservaRoute: typeof AuthenticatedReservaRoute
  AuthenticatedVisaoGeralRoute: typeof AuthenticatedVisaoGeralRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBemVindoRoute: AuthenticatedBemVindoRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedContasRoute: AuthenticatedContasRoute,
  AuthenticatedInvestimentosRoute: AuthenticatedInvestimentosRoute,
  AuthenticatedMetasRoute: AuthenticatedMetasRoute,
  AuthenticatedMovimentacoesRoute: AuthenticatedMovimentacoesRoute,
  AuthenticatedOrganizarSalarioRoute: AuthenticatedOrganizarSalarioRoute,
  AuthenticatedPlanejamentoRoute: AuthenticatedPlanejamentoRoute,
  AuthenticatedReservaRoute: AuthenticatedReservaRoute,
  AuthenticatedVisaoGeralRoute: AuthenticatedVisaoGeralRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
